'use client';

import { useState } from 'react';
import { FileText, Loader2 } from 'lucide-react';
import jsPDF from 'jspdf';

export default function DownloadReportButton({ projectData }: { projectData: any }) {
  const [isDownloading, setIsDownloading] = useState(false);

  const downloadReport = async () => {
    try {
      setIsDownloading(true);
      
      const doc = new jsPDF('p', 'mm', 'a4');
      const pageWidth = doc.internal.pageSize.getWidth();
      let yPos = 20;
      
      const addText = (text: string, size: number, isBold: boolean = false, align: "left" | "center" = "left", color: number[] = [0, 0, 0]) => {
        doc.setFontSize(size);
        doc.setFont('helvetica', isBold ? 'bold' : 'normal');
        doc.setTextColor(color[0], color[1], color[2]);
        
        const lines = doc.splitTextToSize(text, pageWidth - 40);
        
        // Page break logic
        if (yPos + (lines.length * (size * 0.5)) > 280) {
          doc.addPage();
          yPos = 20;
        }
        
        if (align === "center") {
          doc.text(lines, pageWidth / 2, yPos, { align: "center" });
        } else {
          doc.text(lines, 20, yPos);
        }
        
        yPos += lines.length * (size * 0.4) + 6;
      };

      // Title
      addText(`TERRON: Technical & Environmental Dossier`, 18, true, "center", [16, 185, 129]);
      yPos += 5;
      
      // Project Info
      addText(`Project Identification: ${projectData.name || 'Unknown Reference'}`, 12, true);
      addText(`Coordinates: ${projectData.location || 'N/A'} (Lat: ${projectData.lat || 'N/A'}, Lng: ${projectData.lng || 'N/A'})`, 11, false);
      addText(`Constructed Area: ${projectData.area || 0} m2`, 11, false);
      yPos += 5;

      // Analysis Section
      if (projectData.aiAnalysis) {
        const ai = projectData.aiAnalysis;
        
        // Critique
        addText(`Executive Design Critique`, 14, true, "left", [16, 185, 129]);
        addText(String(ai.designCritique || "No critique available."), 10);
        yPos += 5;
        
        // Metrics
        addText(`Performance Metrics`, 14, true, "left", [16, 185, 129]);
        addText(`Terron Integration Score: ${ai.environmentalScore || "N/A"}/100`, 10);
        addText(`Estimated CO2 Reduction: ${ai.co2ReductionEstimate || "N/A"}%`, 10);
        if (ai.calculatedMetrics) {
           addText(`Total Carbon Impact (Lifecycle): ${ai.calculatedMetrics.carbonImpact || 0} tons`, 10);
           addText(`Thermal Baseline Efficiency: ${ai.calculatedMetrics.thermalEfficiency || 0}%`, 10);
        }
        yPos += 5;

        // Recommendations
        if (Array.isArray(ai.keyRecommendations)) {
           addText(`Required Structural Interventions`, 14, true, "left", [16, 185, 129]);
           ai.keyRecommendations.forEach((rec: string, i: number) => {
             addText(`${i + 1}. ${rec}`, 10);
           });
           yPos += 5;
        }

        // Biodiversity
        if (ai.biodiversityImpact) {
           addText(`Ecosystem Integration`, 14, true, "left", [16, 185, 129]);
           addText(String(ai.biodiversityImpact), 10);
           yPos += 5;
        }

        // Eco-Dossier
        if (Array.isArray(ai.ecoDossier)) {
           addText(`Technical Hardware Implementation`, 14, true, "left", [16, 185, 129]);
           ai.ecoDossier.forEach((item: any) => {
             addText(`Asset: ${item.trick || 'N/A'} [Priority: ${item.urgency?.toUpperCase() || 'STANDARD'}]`, 11, true);
             addText(`Target Sector: ${item.location || 'N/A'}`, 10);
             addText(`System Specification: ${item.how || 'N/A'}`, 10);
             addText(`Projected Benefit: ${item.benefit || 'N/A'}`, 10);
             yPos += 3;
           });
        }
      } else {
        addText("Intelligence pipeline has not completed execution. Minimal data retained.", 12);
      }

      // Footer
      yPos = 285;
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by Terron Architectural Intelligence Engine", pageWidth / 2, yPos, { align: "center" });

      // Add Visual References Appendix if images exist
      if (projectData.images && projectData.images.length > 0) {
        doc.addPage();
        yPos = 20;
        addText(`APPENDIX A: Original Reference Materials`, 16, true, "center", [16, 185, 129]);
        yPos += 10;
        
        let imgX = 20;
        for (let i = 0; i < projectData.images.length; i++) {
          try {
            if (imgX > 110) {
              imgX = 20;
              yPos += 80;
            }
            if (yPos > 200) {
              doc.addPage();
              yPos = 20;
            }
            // Safely grab format
            const imgSrc = projectData.images[i];
            const formatMatch = imgSrc.match(/data:image\/([a-zA-Z]*);base64,/);
            const format = formatMatch ? formatMatch[1].toUpperCase() : 'JPEG';
            
            doc.addImage(imgSrc, format === 'SVG+XML' ? 'PNG' : format, imgX, yPos, 80, 60);
            
            // Image caption // Reset font properties properly
            doc.setFontSize(8);
            doc.setTextColor(100, 100, 100);
            doc.text(`Reference Asset 0${i + 1}`, imgX + 40, yPos + 65, { align: "center" });
            
            imgX += 90;
          } catch(err) {
            console.warn(`Could not add image 0${i + 1} to PDF`, err);
          }
        }
      }

      doc.save(`Terron_Intelligence_${projectData.name?.replace(/\\s+/g, '_') || 'Report'}.pdf`);
      
    } catch (e) {
      console.error('Failed to generate PDF', e);
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <button
      onClick={downloadReport}
      disabled={isDownloading}
      className="w-full flex items-center justify-center gap-2 px-8 py-4 rounded-xl font-medium text-lg bg-emerald-500/20 text-emerald-400 border border-emerald-500/50 hover:bg-emerald-500/30 transition-all uppercase tracking-widest disabled:opacity-50"
    >
      {isDownloading ? (
        <>
          <Loader2 className="w-5 h-5 animate-spin" />
          Compiling Dossier...
        </>
      ) : (
        <>
          <FileText className="w-5 h-5" />
          Download Technical Dossier
        </>
      )}
    </button>
  );
}
